version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: rustyindie-pg-c
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: rustyindie
      POSTGRES_USER: rustyindie
      POSTGRES_DB: rustyindie
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  api:
    image: rustyindie-api-i
    container_name: rustyindie-api-c
    build:
      context: .
      dockerfile: ./dev-dockerfile
    depends_on:
      - db
    environment:
      RUST_LOG: debug,
      ENV: development
      PORT: 4003
      HOST: "0.0.0.0"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: rustyindie
      POSTGRES_USER: rustyindie
      POSTGRES_DB: rustyindie
      ALLOWED_LOCAL_WEB_URL: http://127.0.0.1
      ALLOWED_EXT_WEB_URL: http://127.0.0.1
      ALLOWED_ADMIN_URL: http://127.0.0.1:3001
    ports:
      - "4003:4003"
