version: "3.8"

services:
  devdb:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: rustblog
      POSTGRES_USER: rustblog
      POSTGRES_DB: rustblog
    volumes:
      - ./devdb:/var/lib/postgresql/data
