version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: rustyindie-pg-c
    ports:
      - 5433:5432
    env_file: .env.prod
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  api:
    image: rustyindie-api-i
    container_name: rustyindie-api-c
    build:
      context: .
      dockerfile: ./dev-dockerfile
    depends_on:
      - db
    env_file: .env.prod
    ports:
      - "4003:4003"
